#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_godot_toolkit = env_modules.Clone()

env_godot_toolkit.add_source_files(env.modules_sources, "*.cpp")
